// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Environment variable validation
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate required environment variables
const validateEnvironment = (): void => {
  const missingVars: string[] = [];

  if (!SUPABASE_URL) {
    missingVars.push('VITE_SUPABASE_URL');
  }

  if (!SUPABASE_PUBLISHABLE_KEY) {
    missingVars.push('VITE_SUPABASE_PUBLISHABLE_KEY');
  }

  if (missingVars.length > 0) {
    const error = new Error(`Missing required Supabase environment variables: ${missingVars.join(', ')}. Please check your .env file.`);
    console.error('Supabase Configuration Error:', error.message);
    throw error;
  }

  // Validate URL format
  try {
    new URL(SUPABASE_URL);
  } catch {
    const error = new Error(`Invalid SUPABASE_URL format: ${SUPABASE_URL}. Must be a valid URL.`);
    console.error('Supabase Configuration Error:', error.message);
    throw error;
  }

  // Validate key format (basic check for JWT structure)
  if (!SUPABASE_PUBLISHABLE_KEY.startsWith('eyJ')) {
    const error = new Error(`Invalid SUPABASE_PUBLISHABLE_KEY format. Expected JWT token.`);
    console.error('Supabase Configuration Error:', error.message);
    throw error;
  }
};

// Initialize Supabase client with error handling
let supabase: SupabaseClient<Database>;
let connectionStatus: 'connecting' | 'connected' | 'disconnected' | 'error' = 'connecting';

const initializeSupabase = (): SupabaseClient<Database> => {
  try {
    validateEnvironment();

    supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
      global: {
        headers: {
          'X-Client-Info': 'chatsphere/1.0.0',
        },
      },
      // Add connection retry configuration
      db: {
        schema: 'public',
      },
      realtime: {
        params: {
          eventsPerSecond: 10,
        },
      },
    });

    // Test connection
    supabase.realtime.onOpen(() => {
      connectionStatus = 'connected';
      console.log('Supabase connection established successfully');
    });

    supabase.realtime.onClose(() => {
      connectionStatus = 'disconnected';
      console.warn('Supabase connection closed');
    });

    supabase.realtime.onError((error) => {
      connectionStatus = 'error';
      console.error('Supabase connection error:', error);
    });

    return supabase;
  } catch (error) {
    connectionStatus = 'error';
    console.error('Failed to initialize Supabase client:', error);
    throw error;
  }
};

// Initialize the client
try {
  supabase = initializeSupabase();
} catch (error) {
  console.error('Critical: Supabase client initialization failed:', error);
  // Create a mock client that throws errors for all operations
  supabase = new Proxy({} as SupabaseClient<Database>, {
    get() {
      throw new Error('Supabase client is not properly configured. Please check your environment variables.');
    }
  });
}

// Export the client and utilities
export { supabase };

// Export connection status for monitoring
export const getConnectionStatus = (): typeof connectionStatus => connectionStatus;

// Export utility function to check if client is healthy
export const isSupabaseHealthy = async (): Promise<boolean> => {
  try {
    const { error } = await supabase.from('profiles').select('id').limit(1);
    return !error;
  } catch {
    return false;
  }
};

// Export retry utility for failed operations
export const withRetry = async <T>(
  operation: () => Promise<T>,
  maxRetries: number = 3,
  delay: number = 1000
): Promise<T> => {
  let lastError: Error;

  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      return await operation();
    } catch (error) {
      lastError = error as Error;
      console.warn(`Supabase operation failed (attempt ${attempt}/${maxRetries}):`, error);

      if (attempt < maxRetries) {
        await new Promise(resolve => setTimeout(resolve, delay * attempt));
      }
    }
  }

  throw lastError!;
};

// Import the supabase client like this:
// import { supabase, getConnectionStatus, isSupabaseHealthy, withRetry } from "@/integrations/supabase/client";